<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AzunyanModule\Module'                        => __DIR__ . '/Module.php',
    'AzunyanModule\Controller\SkeletonController' => __DIR__ . '/src/AzunyanModule/Controller/SkeletonController.php',
    'AzunyanModuleTest\SampleTest'                => __DIR__ . '/tests/AzunyanModule/SampleTest.php',
    'AzunyanModuleTest\Framework\TestCase'        => __DIR__ . '/tests/AzunyanModule/Framework/TestCase.php',
);
